// Generated by CoffeeScript 1.6.3
/*
*/

var Common, OePartner, Q,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Q = require("q");

Common = require("./common");

OePartner = (function(_super) {
  var partner;

  __extends(OePartner, _super);

  partner = null;

  function OePartner(connector) {
    this.connector = connector;
    this.login = __bind(this.login, this);
    this.fields = ["name", "comercial", "image", "street", "street2", "city", "state_id", "zip", "country_id", "website", "phone", "mobile", "fax", "email", "property_product_pricelist"];
    OePartner.__super__.constructor.call(this, this.connector, "res.partner", this.fields);
  }

  OePartner.prototype.login = function(username, password) {
    var promise,
      _this = this;
    promise = Q.defer();
    this.connector.execute('external.adapter.partner', 'login', username, password).then(function(res) {
      if (res.status === 200) {
        _this.partner = res.data;
        return promise.resolve(_this.partner);
      } else {
        return promise.reject(new Error(res.message));
      }
    }).fail(function(err) {
      return promise.reject(err);
    });
    return promise.promise;
  };

  return OePartner;

})(Common);

module.exports = OePartner;
