// Generated by CoffeeScript 1.6.3
/*
*/

var Common, OeProduct, Q,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Q = require("q");

Common = require("./common");

OeProduct = (function(_super) {
  __extends(OeProduct, _super);

  function OeProduct(connector) {
    this.connector = connector;
    this.getRelatedProducts = __bind(this.getRelatedProducts, this);
    this.getProducts = __bind(this.getProducts, this);
    this.fields = ["name_template"];
    OeProduct.__super__.constructor.call(this, this.connector, "product.product", this.fields);
  }

  OeProduct.prototype.getProducts = function(priceListId, partnerId) {
    return this.connector.execute('external.adapter.product', 'get_products', this.fields, priceListId, partnerId);
  };

  OeProduct.prototype.getRelatedProducts = function(prodId, fields) {
    if (fields == null) {
      fields = this.fields;
    }
    return this.connector.execute('external.adapter.product', 'get_related_products', prodId, fields);
  };

  return OeProduct;

})(Common);

module.exports = OeProduct;
