// Generated by CoffeeScript 1.6.3
/*
*/

var Common, OeSaleOrder, Q,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Q = require("q");

Common = require("./common");

OeSaleOrder = (function(_super) {
  var partner;

  __extends(OeSaleOrder, _super);

  partner = null;

  function OeSaleOrder(connector) {
    this.connector = connector;
    this.fields = ["state"];
    OeSaleOrder.__super__.constructor.call(this, this.connector, "sale.order", this.fields);
  }

  OeSaleOrder.prototype.getByPartner = function(partnerId, fields) {
    if (fields == null) {
      fields = this.fields;
    }
    return this.connector.execute('external.adapter.sale.order', 'get_by_partner', partnerId, fields);
  };

  return OeSaleOrder;

})(Common);

module.exports = OeSaleOrder;
